name: untitled
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fl_chart: ^0.65.0
  csv: ^5.1.1
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Lead1.csv
    - assets/Lead2.csv
    - assets/Lead3.csv
    - assets/V1.csv
    - assets/V2.csv
    - assets/V3.csv
    - assets/V4.csv
    - assets/V5.csv
    - assets/V6.csv
    - assets/avf.csv
    - assets/avl.csv
    - assets/avr.csv
